server:
  port: 8080

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

    static-path-pattern: /resources/** 
 
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: green
    password: green1234
    url: jdbc:mariadb://localhost:3306/greendb?serverTimezone=Asia/Seoul
    
  jpa:
    hibernate:
      ddl-auto: create  # create, none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true       
